### ISSUE TITLE
R Study group 2018 planning session

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#1]
Curious about the R study group (https://ubc-r-study-group.github.io/studyGroup/)? Want to learn R/ Python and don't know where to start? Have a cool package/ tool that you want to share with the community?

Come to the first study group meetup of 2018 Fall! </br>
**Time:** Wednesday, Sept 12, 12:30-1:30PM
**Place:** Koerner Library (Room 216)

We will talk about topics YOU are interested in and schedule the fall sessions. Come help us plan out this year and sign up for a GitHub account if you don't have one.

In the past, we have run various utility Belt sessions, which are aimed at beginners (and will cover various R packages in tidyverse on data manipulation and visualization). If there is interest, we will also work through Hadley Wickham's Advanced R book http://adv-r.had.co.nz/. 

We would also like to hear from the community the topics they are interested in. So come on out and share your ideas with us.

Hope to see you all there!

The R Study Group Organizing Team

**Comment by ttimbers** [comment]
@minisciencegirl -  Here is a table we can fill in as people volunteer to give sessions. I have just selected some chapters from some of the books we've been talking about as a guide. We can easily change these.

| Date             | Topic                                                                              | Name | GitHub username   |
|-------------|---------------------------------------------------|-----------------|----------| 
| 2018-09-19 | Chapter 3 Data visualisation (R for Data Science)   | Deirdre Loughnan |  DeirdreLoughnan |  
| 2018-09-26 | Chapter: Functions (Advanced R)  | Arzan Irani  | nazra-inari   |
| 2018-10-03  | Work-a-long or flex session |   |   |
| 2018-10-10 | Chapter 5 Data transformation (R for Data Science)   | Allison Mann |  aemann01  |  
| 2018-10-17  |  Chapter: OO field guide (Advanced R)  | Ian Flores | ian-flores         |
| 2018-10-24  | Time series and Julia | Arnav Sood   | arnavs   |
| 2018-10-31 | Chapter 7 Exploratory Data Analysis (R for Data Science)   | Aaron Quinton | aaronquinton |  
| 2018-11-07 | Chapter: Data structures (Advanced R)  |  Milos Milic                 | milicmil         |
| 2018-11-14 | Work-a-long or flex session |   |   | 
| 2018-11-21 | Shiny in R   | Amin Adibi | aminadibi  |  
| 2018-11-28 | R Markdown   | Tiffany Timbers                    | ttimbers    |
| 2018-12-05 | Holiday social |   |   |

**Comment by ttimbers** [comment]
Links to Books:
- [R for Data Science](http://r4ds.had.co.nz/)
- [Advanced R](http://adv-r.had.co.nz/)

**Comment by arnavs** [comment]
Closing as it's now 2019 `:-)`
