### ISSUE TITLE
Help with R

### ISSUE THREAD

**Issue by eamimo** [UBC-R-Study-group/studyGroup#112]
Hi all,

I attended one workshop of your group prior to having my 3rd child. And I really liked how it was framed. I'm a grad student at the Faculty of Forestry and I want to learn using R, because is the one thing I've struggled a lot during the drafting of my first chapter. I have attended several trainings/workshops (paid and free) with no luck. I wonder if there is any one-on-one consulting hour in place. I could pay 1 hour, 1 a week for 1 or 2 months. I am hoping to run anovas and prepare nice graphs (w/SE or SD on them). I have several species (5+) and treatments (3+)

Looking forward to hearing from you,

Cheers,

Estefanía (She, Her, Hers)
emilla@alumni.ubc.ca

**Comment by laijasmine** [comment]
Hi Estefania,

There is one on one online consulting available through the UBC library on a variety of topics (including R and Thesis formatting): https://researchcommons.library.ubc.ca/consultation-requests/

You can also contact them at: research.commons@ubc.ca

There is also the R for Data Science slack group that I have heard good things about here for any help:
https://www.rfordatasci.com/

Best,

Jasmine

**Comment by eamimo** [comment]
Thank you so much, Jasmine. I just registered an appointment on RC and subscribed in the slack group.

Best,


Estefania
