### ISSUE TITLE
Introductions and RMarkdown Tutorial: Wednesday, January 13th, 1-2pm

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#115]
Happy New Year! Kick off your academic pursuits this year by attending the first 2021 meeting of the UBC R Study Group. Our opening session will occur on Wednesday January 13th, from 1-2pm. We'll start with brief introductions and a (tentative!) schedule for the term, followed by a short lesson on RMarkdown.

Because of the restrictions in place due to Covid-19, this meeting (and all of our meetings for this term) will be held virtually on Zoom. Check back here on the 13th for the Zoom link.

**Comment by travis-m-blimkie** [comment]
Good morning! Below is the Zoom info for today's meeting. Note that you will need to be signed in to Zoom in order to join. 

If you wish to code along, you'll need to install the following R packages:
`install.packages(c("tidyverse", "rmarkdown", "kntir", "DT"))`

See everyone at 1pm!

Topic: UBC R Study Group - Jan13
Time: Jan 13, 2021 01:00 PM Vancouver

Join Zoom Meeting
https://ubc.zoom.us/j/61712561634?pwd=alJjUDM5RFBBSFBIRFlTV0pUSkVMdz09

Meeting ID: 617 1256 1634
Passcode: 414337

One tap mobile
+17789072071,,61712561634#,,,,,,0#,,414337#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 617 1256 1634
Passcode: 414337

Join by SIP
61712561634@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 617 1256 1634
Passcode: 414337

**Comment by travis-m-blimkie** [comment]
Here are the notes from today's lessons!
https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons/20210113

**Comment by AmyMatsubara** [comment]
Thank you the session and restarting the study group, Travis and Jeremy! I wanted to thank you on Zoom but it froze on me.
