### ISSUE TITLE
High-quality graphics with ggplot2 and beyond: Wednesday, January 27th, 1-2pm

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#117]
This weeks session will focus on creating publication quality plots right from RStudio. Content will be focused on ggplot2, but with some additional tweaks from the `cowplot` and `ggtext` packages. We will also cover the creation of interactive plots via the `plotly` package. Check back here on the 27th for a Zoom link.

Cheers!

**Comment by travis-m-blimkie** [comment]
Hello everyone! Please the info below for a Zoom link to join today's session at 1pm. Note that as usual you need to be signed in to Zoom in order to join. There are also a few packages we'll be using today, so if you'd like to code along be sure to install these before the session: 
`install.packages(c("cowplot", "plotly", "ggtext", "tidyverse", "gapminder"))`

That's all for now! See you this afternoon.

Topic: UBC R Study Group
Time: Jan 27, 2021 01:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/65576958909?pwd=NDNKMDd0bDVKUmU5Q2V6OVdNUG5oZz09

Meeting ID: 655 7695 8909
Passcode: 623395

One tap mobile
+17789072071,,65576958909#,,,,,,0#,,623395#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 655 7695 8909
Passcode: 623395

Join by SIP
65576958909@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 655 7695 8909
Passcode: 623395

**Comment by travis-m-blimkie** [comment]
Hello again! Here is the link for today's lesson: https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons/20210127  The Rmd file can be viewed in RStudio, while the HTML can be viewed in a web browser. 

And to follow up on the custom theme discussion, here is one I myself use (modified from `theme_light`):
```{r}
my_theme <- function(baseSize = 16, baseFamily = "") {
  theme_light(base_size = baseSize, base_family = baseFamily) +
    theme(
      text             = element_text(colour = "black"),
      axis.text        = element_text(colour = "black"),
      axis.ticks       = element_line(colour = "black", size = 0.5),
      panel.grid.major = element_line(colour = "grey", size = 0.5),
      panel.grid.minor = element_blank(),
      panel.border     = element_rect(colour = "black", size = 1),
      strip.background = element_rect(fill = NA),
      strip.text       = element_text(colour = "black", face = "bold", size = 14)
    )
}
```
Just run the function to add it to the environment, then call it like any of the other ggplot2 theme functions.

Cheers & thanks to everyone who came out today!

**Comment by zhemingfan** [comment]
Thank you @travis-m-blimkie! You can find more information about the kin of parameters you can play with [here](https://ggplot2.tidyverse.org/reference/theme.html). And a guide by RPubs can be found [here](https://rpubs.com/mclaire19/ggplot2-custom-themes). I think the dataset might be slightly outdated, so feel free to play with some other datas you might have!
