### ISSUE TITLE
Intro to data manipulation with the tidyverse: Wednesday, February 3rd, 1-2pm

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#118]
This week we will provide a introduction to using tidyverse functions to clean, organize, manipulate and edit your data in R. Check back on the 3rd for a Zoom link.

Cheers,

**Comment by travis-m-blimkie** [comment]
Morning all! Please see the Zoom information for today's session below. As usual, you will need to be signed in to Zoom to join the meeting. If you'd like to code along during the lesson, please make sure you have the tidyverse installed beforehand; you can do so using the command `install.packages("tidyverse")`.

Cheers!

Topic: UBC R Study Group
Time: Feb 3, 2021 01:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/62344792180?pwd=d05rN296c1V5Rjg2OGQyRVlhSUhPZz09

Meeting ID: 623 4479 2180
Passcode: 774014

One tap mobile
+17789072071,,62344792180#,,,,,,0#,,774014#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 623 4479 2180
Passcode: 774014

Join by SIP
62344792180@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 623 4479 2180
Passcode: 774014

**Comment by zhemingfan** [comment]
Thank you everyone for coming! Notes can be found [here](https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons/20210203) !
