### ISSUE TITLE
Writing functions in R: Wednesday, February 10th, 1-2pm

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#119]
Would you like to learn how to supercharge your R code by creating your own functions? Then come to our live coding lesson on Wednesday, February 10th, from 1-2pm. As usual, this session will be held over Zoom (account required), so be sure to check back here on the 10th for the link. 

Cheers!

**Comment by razibayati** [comment]
How can I register for your events?

**Comment by travis-m-blimkie** [comment]
Hi there! Thanks for your interest in the event, and for reaching out with your question. 
The only requirement to join is to be signed in to a Zoom account (available for free from them); there's no signup or registration for the session itself. I will be posting the Zoom link/info a couple hours before the session itself, which starts at 1pm. Hope to see you there!

Cheers!

**Comment by travis-m-blimkie** [comment]
Hi everyone! Please see below for the Zoom information for today's session. As usual, you will need to be signed into Zoom in order to join. If you'd like to code along with us today, please make sure you have the tidyverse installed; you can use the code `install.packages("tidyverse")` if you need to add it. 

Cheers!

Topic: UBC R Study Group: Writing Functions in R
Time: Feb 10, 2021 01:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/67803600091?pwd=clFJYW5rS2VGLzF0Z1h4alFqcVNGZz09

Meeting ID: 678 0360 0091
Passcode: 178598

One tap mobile
+17789072071,,67803600091#,,,,,,0#,,178598#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 678 0360 0091
Passcode: 178598

Join by SIP
67803600091@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 678 0360 0091
Passcode: 178598

**Comment by travis-m-blimkie** [comment]
Thanks to everyone who was able to make it to today's lesson! As mentioned, here is a link to the notes/scripts from today:
https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons/20210210

Cheers!
