### ISSUE TITLE
Exploratory Data Analysis in R

### ISSUE THREAD

**Issue by ian-flores** [UBC-R-Study-group/studyGroup#12]
Come learn about Exploratory Data Analysis in R as we work through the  Exploratory Data Analysis chapter from R for Data Science

Session Led by @aaronquinton

**Where**: Koerner Library, UBC, Room 216

**When**:
October 31, 2018 at 01:00:00 PM

**Comment by aaronquinton** [comment]
Hi everyone! I will be doing some live coding as we discuss exploratory data analysis tomorrow. To code along with me make sure you have the following things installed.

1. Rstudio 

2. R Packages 
- tidyverse
- ggbeeswarm
(to install packages type `install.packages("tidyverse")` and `install.packages("ggbeeswarm")` in the R console.

We will be exploring through a csv on my repository. But not to worry about this right now, we will load it together tomorrow using the link below.
"https://raw.githubusercontent.com/aaronquinton/Rstudygroup_EDA/master/Data/avocado.csv"

**Comment by aaronquinton** [comment]
Thank you for attending the Exploratory Data Analysis session. For those that were interested, below is a link to my git hub repository. Scroll down to the  README which can direct you to the presentation slides, live coding script, and other relevant files. 

https://github.com/aaronquinton/Rstudygroup_EDA

**Comment by arnavs** [comment]
Great talk, thanks for giving it!
