### ISSUE TITLE
Shiny Apps in R: Wednesday, February 24th, 1-2pm

### ISSUE THREAD

**Issue by zhemingfan** [UBC-R-Study-group/studyGroup#120]
Would you like to learn how to develop robust applications using Shiny in R? We'll be running a workshop to develop a dashboard that can be used for visualization that can be published on Shinyapps.io!

Join us for our live coding lesson on Wednesday, February 24th, from 1-2pm to get a hands-on tutorial on how RShiny works, and publish your application! As usual, this session will be held over Zoom (account required), so be sure to check back here for the link.

**Comment by travis-m-blimkie** [comment]
Morning all! Below is the Zoom information for today's session on Shiny. As usual, a Zoom account is required to join the meeting. Cheers!

Topic: UBC R Study Group
Time: Feb 24, 2021 01:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/61829140856?pwd=T05VWUg1Tjk2Rm9pTllMd0dJZXdCdz09

Meeting ID: 618 2914 0856
Passcode: 595088

One tap mobile
+17789072071,,61829140856#,,,,,,0#,,595088#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 618 2914 0856
Passcode: 595088

Join by SIP
61829140856@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 618 2914 0856
Passcode: 595088

**Comment by travis-m-blimkie** [comment]
Thanks Jeremy for the great intoduction to Shiny! Here's a link to the example app and lesson from today. Cheers!

https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons/20210224/ShinyDemoApp
