### ISSUE TITLE
new member

### ISSUE THREAD

**Issue by razibayati** [UBC-R-Study-group/studyGroup#121]
Hey, I am wondering if you have recorded previous sessions and if it is available to watch? 
Also, how can I be a member of your reading group? 

cheers,
Razi

**Comment by travis-m-blimkie** [comment]
Hi Razi, 

Unfortunately our lessons are not recorded. However, all of our materials are on our Github page in the "lessons" folder, and organized by date. [Here's](https://github.com/UBC-R-Study-group/studyGroup/tree/gh-pages/lessons) a direct link for you.

Regarding membership, you are free to join our regular sessions whenever you like; there's no sign up or registration needed to attend. If you're interested in teaching a lesson, or would like to be involved in the organization of the study group, let me know and we can take some time right before or after our next session to chat about it in more detail.

Hope that answers your questions. 

Cheers!
