### ISSUE TITLE
Using git with RStudio: Wednesday, March 17th, 1-2pm

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#126]
Enjoyed last week's lesson on git, but feeling like you need something more hand-on? Come out to the virtual R Study Group on Wednesday the 17th for our practical git+RStudio lesson! For this week there will be a few prerequisites if you wish to follow along:

- Set up a [Github account](https://github.com/join)
- Ensure git is installed on your computer
    - For Windows: [Install git for Windows](https://git-scm.com/download/win)
    - For Mac: [Install git for Mac](https://git-scm.com/download/mac)

As usual a Zoom account will be required to join the session - link/details will be posted here on the day of the event.

That's all for now folks! Cheers!

**Comment by hectorpl** [comment]
Thank you Travis

**Comment by travis-m-blimkie** [comment]
Morning! Please see below for Zoom details. As usual you will need a Zoom account in order to join. And if you wish to follow along, make sure you have a Github account and have git installed on your computer (see instructions above). Cheers!

Topic: Using git with RStudio: UBC R Studygroup
Time: Mar 17, 2021 01:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://ubc.zoom.us/j/67802811810?pwd=RjZ5dE1KMDNHTVg0Nmg3d2ljdmtyZz09

Meeting ID: 678 0281 1810
Passcode: 190237

One tap mobile
+17789072071,,67802811810#,,,,,,0#,,190237#

Dial by your location
+1 778 907 2071 (Vancouver)
+1 647 374 4685 (Toronto)
+1 647 375 2970 (Toronto)
+1 647 375 2971 (Toronto)
+1 204 272 7920 (Manitoba)
+1 438 809 7799 (Montreal)
+1 587 328 1099 (Alberta)
+1 613 209 3054 (Ottawa)

Meeting ID: 678 0281 1810
Passcode: 190237

Join by SIP
67802811810@zmca.us

Join by H.323
69.174.57.160 (Canada)
Meeting ID: 678 0281 1810
Passcode: 190237

**Comment by travis-m-blimkie** [comment]
Here's a direct link to the lesson outline from last week. Cheers for now!

https://github.com/UBC-R-Study-group/studyGroup/blob/gh-pages/lessons/20210317/lesson.md
