### ISSUE TITLE
Vancouver DataJam 2021 (September 18-25)

### ISSUE THREAD

**Issue by laijasmine** [UBC-R-Study-group/studyGroup#133]
Are you looking for professional development and portfolio-building opportunities in the data science sector? Join data science enthusiasts for the Vancouver DataJam: a virtual event with a focus on supporting members of gender and racial minorities get their careers in data science kickstarted.

Learn about our event: https://www.vancouverdatajam.ca/

The event will be hosted 100% virtually from September 18-25 2021. The event starts with workshops in R, Python, GitHub, and more. Participants will then have the opportunity to gain hands on experience in data science via a series of projects. Join the Vancouver DataJam either as a participant or team lead!

Learn about our workshops in Python, R and GitHub: https://www.vancouverdatajam.ca/workshops

If you want to lead
The project call for proposals is open for data-science project ideas tackling COVID19 recovery at the social, public health, economic and sustainable dimensions.
Submit your project idea https://lnkd.in/gcUH3KJ

If you want to participate
You don't need to lead a project project idea to contribute to a project during the Vancouver DataJam.
Sign-up as a participant https://lnkd.in/g3css-F

NOTE:
To get Zoom and Discord information please fill out one of the team lead or participant forms.

**Comment by hectorpl** [comment]
Hi Jasmine, is it open to everyone? Thanks

**Comment by laijasmine** [comment]
Hi Hector! Yes it is open to everyone but we are trying to focus on individuals living around Vancouver.

**Comment by hectorpl** [comment]
Perfect 😀 Thanks!
