### ISSUE TITLE
Call for TA applications for MDS and BAIT 580A for 2022 Winter Term 2

### ISSUE THREAD

**Issue by zmx721** [UBC-R-Study-group/studyGroup#139]
Dear UBC R Study Group,

We are now accepting applications for TAships with the UBC Master of Data Science (MDS) program and related course BAIT 580A in 2022 Term 2 (January 2023 to April 2023). Please complete and submit the following form if you are interested: https://ubc.ca1.qualtrics.com/jfe/form/SV_0AJAWzVa2STZjQa

The soft deadline to apply is Oct 21 2022. The Term 2 course offerings span machine learning, data visualization, collaborative software development, cloud computing, and more. (If you want to know the exact courses, check out courses from blocks 4, 5, and 6 [here](https://ubc-mds.github.io/descriptions/).) With the MDS schedule, it is possible to TA for only portions of the term, which may be appealing to those who are not available for the entire term.

We hope you will consider working with us! If you have any questions about this (or anything related) please do not hesitate to email me :)

Best,
Betty Zhao
Course Coordinator,
Master of Data Science program
betty.zhao@ubc.ca

**Comment by travis-m-blimkie** [comment]
Closed as deadline has passed.
