### ISSUE TITLE
Shiny in R

### ISSUE THREAD

**Issue by ian-flores** [UBC-R-Study-group/studyGroup#15]
Come learn about Shiny in R

Session Led by @aminadibi

**Where**: Koerner Library, UBC, Room 216

**When**:
November 21, 2018 at 01:00:00 PM

**Comment by aminadibi** [comment]
Hi everyone, 

I'm super-exited for our R Shiny session tomorrow. We'll code together, step by step, to build a simple  web app: [https://shefa.shinyapps.io/vancity-income/](https://shefa.shinyapps.io/vancity-income/)

Except for basic R, no previous knowledge is necessary.  However, if you'd like to code along with me please make sure you have RStudio with R v3.5.1. I'd also recommend you install the following packages before we meet, so we can start right away:
`install.packages(c("shiny","sf", "ggplot2", "leaflet", "shinythemes"))`

The GitHub repository which includes the data file, instructions, and the final code can be found here:
https://github.com/aminadibi/UBC-Shiny/tree/master

See you tomorrow!

**Comment by aminadibi** [comment]
Here's a useful Shiny cheatsheet! https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf

**Comment by aminadibi** [comment]
Plotly Dash is some kind of Shiny equivalent for Python: https://plot.ly/products/dash/
