### ISSUE TITLE
R Markdown

### ISSUE THREAD

**Issue by ian-flores** [UBC-R-Study-group/studyGroup#16]
Come learn about R Markdown, a reproducible document format. 

Session Led by @ttimbers 

Where: Koerner Library, UBC, Room 216

When:
November 28, 2018 at 01:00:00 PM

**Comment by minisciencegirl** [comment]
@travis-m-blimkie @abaghela and I will go through this lab from the MDS public repo!
https://github.com/UBC-MDS/public/blob/master/courses/521_platforms/release/lab3/lab3.Rmd

Please make sure to have `knitr` installed!!
