### ISSUE TITLE
Call for TA applications for the Master of Data Science (MDS) program, 2018W2 (Jan-Apr 2019)

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#17]
Hi all,

We have opened TA applications for the Master of Data Science (MDS) program for Term 2. This is a great opportunity to teach and learn more about data science and and machine learning. If you are interested in being a TA in the Spring, please fill out this application form: https://ubc.ca1.qualtrics.com/jfe/form/SV_cAZwboSVSIVN3h3. You'll find a list of courses, and more info about them, embedded in this application form.

The deadline to apply is **Friday, Oct 26**. We might still keep the application form open after that, but you should apply by then to receive full consideration. Looking forward to hopefully working with some of you!

Best,
Tiffany

**Comment by arnavs** [comment]
Closing as deadline for the applications has passed.
