### ISSUE TITLE
Website, repo and slack URLs

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#2]
GitHub repo: https://github.com/UBC-R-Study-group/studyGroup

website: https://ubc-r-study-group.github.io/studyGroup/

where we used to live: https://github.com/minisciencegirl/studyGroup

old issues (previous topics covered): https://github.com/minisciencegirl/studyGroup/issues 

Slack: ubrstudygroup.slack.com, with invite link https://join.slack.com/t/ubcrstudygroup/shared_invite/enQtNzg3MzA1NzE0NDcwLTM1YjBiMzM4N2FiNzVmZmJkMDkyYzQyMTJiOGUzZTE2YzdkYTQzODU4Yjg5MGZlYTBjNDM1YzEzMTVkMGQ2OWE

**Comment by minisciencegirl** [comment]
~Slack: ubc-r-study-group.slack.com~

New Slack: ubrstudygroup.slack.com, with invite link https://join.slack.com/t/ubcrstudygroup/shared_invite/enQtNzg3MzA1NzE0NDcwLTM1YjBiMzM4N2FiNzVmZmJkMDkyYzQyMTJiOGUzZTE2YzdkYTQzODU4Yjg5MGZlYTBjNDM1YzEzMTVkMGQ2OWE

**Comment by arnavs** [comment]
Currently you can only create an account if you work at the University of Wisconsin (`@wisc.edu`). See: https://ubc-r-study-group.slack.com/signup

**Comment by minisciencegirl** [comment]
Hey @arnavs, please go to https://slack.com/signin, and then enter in `ubc-r-study-group`

**Comment by arnavs** [comment]
I think that's the signin page for when you already have an account (so I guess, if you have an existing account with a UBC domain or something, you're good). But it seems like you can't make a new account in the workspace without that domain.

**Comment by minisciencegirl** [comment]
OK let me check in with @JoeyBernhardt and see how this slack workspace was created originally.

**Comment by laijasmine** [comment]
Updated slack url: https://join.slack.com/t/ubcrstudygroup/shared_invite/enQtNzg3MzA1NzE0NDcwLTM1YjBiMzM4N2FiNzVmZmJkMDkyYzQyMTJiOGUzZTE2YzdkYTQzODU4Yjg5MGZlYTBjNDM1YzEzMTVkMGQ2OWE

**Comment by arnavs** [comment]
I think if we close this it will still stay pinned. Might as well.
