### ISSUE TITLE
Holiday social reminder and planning

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#22]
Hi folks! 

This is a reminder of our holiday social on Wednesday Dec 5th at 1pm in Koerner Library, room 216.

We were thinking potluck. I will provide some eggnog, what will you all bring? Please post below in this thread. Also, can someone volunteer to get together some music to play. If anyone is keen on decorating, that is welcome too!

Cheers!

**Comment by aaronquinton** [comment]
Hi! I will be bringing some baked goods. I have a smart speaker and lots of Christmas music (albeit with a huge bias towards Michael Buble) that I can bring as well.

I also know some MDS folk who might be coming after the alumni talk. I’ll try and convince them to bring food.

**Comment by arnavs** [comment]
I'll be in tomorrow with some soda and chips. (chocolate stuff too?)

**Comment by heathervant** [comment]
i can bring chips and salsa at 12:35! (hoping to go to the alumni talk first)

**Comment by minisciencegirl** [comment]
I will be there! I will bring a coffee cake.

**Comment by rzitomer** [comment]
I'll be there! I can bring an assortment of nuts.

**Comment by mru4913** [comment]
I will bring chips.

**Comment by travis-m-blimkie** [comment]
I am bringing mini cupcakes!

**Comment by arnavs** [comment]
Actually don't think I can make it, but have fun `:-)`
