### ISSUE TITLE
Winter 2019

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#24]
Will this group be meeting this semester?

**Comment by ttimbers** [comment]
Yes! I think there will be a very informal meeting today at 1 in Koerner 216, and then actually start formally next week. Please come today if you can/want!

**Comment by arnavs** [comment]
Perfect, I'm in.

**Comment by ttimbers** [comment]
# Brainstorming

## What do we want to learn?
- data types, how to write functions
- `purrr`'s map functions, loops, apply (Travis - @travis-m-blimkie Feb)
- NSE (non-standard evaluation - tidy evaluation) (Amy @minisciencegirl )
- simple/intro visualization (`ggplot2`, scatter plots, histograms) (Richie @rzitomer mid/late Feb)
- more advanced viz (`pheatmap`, network diagrams via `igraph` or `ggraph`?) (& clustering)?
- exploratory data analysis (Aaron @aaronquinton early March)
- dimensionality reduction & viz (PCA, t-sne)  (& clustering)?
- machine learning (Ian @ian-flores March)
- R packages (group project 2) (Tiffany @ttimbers kick-off before group project - end of March/early april)
- Shiny (group project)
- Julia
- NLP
- data cleaning/munging (group project 1)

## Should we organize our own beginner workshop?
- will take some weeks to get organized? Maybe in February?
- 3hr long, covering basic dataframe manipulation and data viz using tidyverse
- any volunteers interested in helping with teaching and organizing?
- use Data Carpentry/Software Carpentry materials 
- plan out at next session (which will be a co-working session)

**Comment by brian604** [comment]
Hello, I am Jiwon Kim who came yesterday for first session. 
I have a time conflict because I have a class (MWF 1:00 PM~ 2:00 PM; Also I have TueThu 11~12, 2:00 ~ 3:00 PM)

**Comment by brian604** [comment]
Hello, this is just a side-note. 
I would like to publicize a project I will start to work on, and I believe that R-study group page is hosted by GitHub. 
Could any of you teach me how, to make a website using Github?

**Comment by arnavs** [comment]
@brian604 My [personal website](http://arnavsood.com) is hosted through github (https://github.com/arnavs/website is the source repository). 

Send me an email at `arnav.sood@ubc.ca` and I can try and help you out.

**Comment by ian-flores** [comment]
@ttimbers @minisciencegirl @arnavs - I can collaborate for the 3hr workshop covering the tidyverse. 

Also for the talk about Machine Learning in R, I can do it the first week of March on the 6th.

**Comment by arnavs** [comment]
I can do the `julia` one (if that's something people want, I know at least one person two weeks ago was interested). Late March would probably be best. I've figured out how to set up my own JupyterHub for the talk, so no more technical issues `:-)`

**Comment by laijasmine** [comment]
interested in helping out with organizing/teaching the beginner workshop! Hopefully I can get out of my lab meeting to come to the planning session.

**Comment by minisciencegirl** [comment]
Beginner  workshop planning will be issue #27.

We've tentatively set the schedule for our winter session below. If the time doesn't work for you, please let us know and switch it with one of the work-a-longs. Thank you!

| Date        | Topic                                             | Name            | GitHub username   |
|-------------|---------------------------------------------------|-----------------|-------------------|
| 2019-01-30  | Work-a-long and Planning                          |                 |                   |
| 2019-02-06  | Workshop Planning                                 |                 |                   |
| 2019-02-13  | Workshop Planning                                 |                 |                   |
| 2019-02-20  | Intro Plotting (`gg`, scatter, histograms, etc.)  | Richie Zitomer  | @rzitomer          |
| 2019-02-27  | Work-a-long                                       |                 |                   |
| 2019-03-06  | Exploratory Data Analysis                         | Aaron Quintin   | @aaronquinton      |
| 2019-03-13  | Work-a-long                                       |                 |                   |
| 2019-03-20  | Machine Learning in R                             | Ian Flores      | @ian-flores        |
| 2019-03-27  | Work-a-long                                       |                 |                   |
| 2019-04-03  | The Julia Programming Language                    | Arnav Sood      | @arnavs            |
| 2019-04-10  | Work-a-long                                       |                 |                   |
| 2019-04-17  | `purr`                                            | Travis Blimkie  | @travis-m-blimkie  |
| 2019-04-24  | Work-a-long                                       |                 |                   |
| 2019-05-01  | Non-Standard Evaluation in R                      | Amy Lee         | @minisciencegirl   |
| 2019-05-08  | Group Project Presentations/Party                 |                 |                   |
| 2019-05-15  | End-of-year Party                                 |                 |                   | 

@ian-flores and @travis-m-blimkie: would you guys be able to create issues/ post for the scheduled sessions?
