### ISSUE TITLE
Introduction to dataframe manipulation using dplyr and mini work-along session

### ISSUE THREAD

**Issue by minisciencegirl** [UBC-R-Study-group/studyGroup#25]
Come learn about dplyr (from the tidyverse package), a workhorse in dataframe manipulation and your start to reproducible data analyses. We will finalize our winter semester's schedule (see #24 for suggested topics), followed by a brief 15-20 min talk and code-along with dplyr. 

Session Led by @travis-m-blimkie

Where: Koerner Library, UBC, Room 216

When: Jan 23, 2019 at 01:00:00 PM

Install: install.packages("tidyverse")
* If you run into installation problems, please come by a bit earlier and we can help you troubleshoot.

**Comment by levanayang** [comment]
Hi, are you guys having a different meeting on the 23rd? I came here from the website which said Jan 23rd, but it looks like I already missed this one :'(

**Comment by travis-m-blimkie** [comment]
Hello, the meeting next week on the 23rd will be on the things mentioned above (finalizing topics and an intro to dplyr). I think the date just got mixed up. It will still be at 1pm.

**Comment by arnavs** [comment]
I updated the date to 23.

**Comment by minisciencegirl** [comment]
Thanks @travis-m-blimkie and @arnavs!

**Comment by travis-m-blimkie** [comment]
Hello everyone!

As mentioned, I will be giving a brief (~15 minute) introduction to `dplyr`. 

The script we will be using can be downloaded at the following link:
https://raw.githubusercontent.com/travis-m-blimkie/misc_files/master/Scripts/dplyr_tutorial_lesson.R

To download the script, right-click anywhere on the page and save into a folder of your choosing. Then simply open the file with RStudio. We will be going through this script together as a live coding exercise, but feel free to take a look beforehand. 

Please make sure you have R/RStudio up and running. You can install tidyverse (which includes dplyr) with the following command:
`install.packages("tidyverse")`

This lesson is based upon a Software Carpentry lesson, available at:
http://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html

If you have any difficulties with the installation, either myself or someone else at the session will be able to help.

Cheers!

**Comment by travis-m-blimkie** [comment]
I have added the script from today's lesson to the `lessons` folder of the repo for people to download and run themselves.
Cheers!
