### ISSUE TITLE
Beginner R workshop planning

### ISSUE THREAD

**Issue by minisciencegirl** [UBC-R-Study-group/studyGroup#27]
Come join us on Feb 6 and Feb 13 for our R workshop planning. Bring ideas, code and we can do some demo teaching together. Our plan is to teach dplyr, tidyr and ggplot2.

Our plan is to run the session on **March 8, 1-4PM**. Location TBD

@arnavs @ttimbers @laijasmine @travis-m-blimkie @ian-flores

**Comment by minisciencegirl** [comment]
@arnavs @laijasmine @travis-m-blimkie @ian-flores: Are you guys available on March 8?

**Comment by arnavs** [comment]
Yeah

**Comment by laijasmine** [comment]
works for me!

**Comment by travis-m-blimkie** [comment]
I am free!

**Comment by ttimbers** [comment]
Teach from these materials?

http://swcarpentry.github.io/r-novice-gapminder/

https://datacarpentry.org/R-ecology-lesson/

**Comment by minisciencegirl** [comment]
Things to do:

- Write an event post and create eventbrite (make sure to ask if the attendee has UBC CWL, if not use pims.syzygy.ca)
- Advertise
- Where to pull the course materials from?
- Instructors: 
@ian-flores ggplot2
@aaronquinton dplyr
@travis-m-blimkie dplyr
@laijasmine ggplot2
@arnavs intro to jupyter/syzgy
- Helpers: @ttimbers @minisciencegirl @awakenedhaki
- Book room
- Host the workshop on https://ubc.syzygy.ca/
- Make a public github repo for the lessons, with a ReadMe and data directory
- Pick up coffee/ snacks/ post-it notes

**Comment by ttimbers** [comment]
Use Jupyter for the workshop, links are here:

- https://ubc.syzygy.ca/
- https://pims.syzygy.ca/ (backup)

**Comment by minisciencegirl** [comment]
| Instructor  | Lesson  |
|------------|---------|
|@arnavs  | intro to jupyter/syzgy |
|@ian-flores  | ggplot2  |
|@aaronquinton  | tidyr/dplyr | 
|@travis-m-blimkie  | tidyr/dplyr |
|@laijasmine | ggplot2 |

**Comment by ttimbers** [comment]
10 tips and tricks for instructing and teaching by means of live coding
https://software-carpentry.org/blog/2016/04/tips-tricks-live-coding.html

Two examples of live coding, one good, one bad:
- https://www.youtube.com/watch?v=Vacuk_kNOz8
- https://www.youtube.com/watch?v=T5FKByBEe0c

**Comment by aaronquinton** [comment]
Hey @travis-m-blimkie,

For our section of the workshop we had initially discussed splitting up tidyr/dplyr, with me teaching  tidyr. Would you be able and wanting to take the entire section?

I am still able to attend the workshop as a helper, but do to other obligations this week I am not confident in my ability to prepare material and comfortably present it on Friday.

**Comment by minisciencegirl** [comment]
Hi @aaronquinton: Travis and I managed to get a fellow labmate @abaghela to take that session. How are the rest of instructors (@travis-m-blimkie, @laijasmine, @ian-flores, @arnavs) doing? Do you guys want to meet half an hour early on Friday to do a quick dry run?

**Comment by arnavs** [comment]
Sure, that works for me. Haven't written my piece up yet, will do tonight.

**Comment by laijasmine** [comment]
@minisciencegirl We will probably need to move the desks to the right configuration 🤣 See you all at 12:30 then?
