### ISSUE TITLE
For loop plot output to grid

### ISSUE THREAD

**Issue by j3551ca** [UBC-R-Study-group/studyGroup#29]
Hello! I've written a loop to plot 70 figures that look like this:

![screen shot 2019-02-08 at 3 28 02 pm](https://user-images.githubusercontent.com/39065261/52511710-21a4c700-2bb6-11e9-9dce-6712c829ed64.png)

```
start<-c(19, 22, 27, 84, 29, 22, 29, 39, 19, 8)
stop<-c(3891, 2304,  2090, 2342, 1021, 1284, 1093, 986,  3867, 3868)
x=3934

for (i in 1:10){
ggplot(all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),], aes(all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),2], all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),18])) + geom_line() + scale_x_continuous(limits=c(0,4000), expand=c(0,0)) + scale_y_continuous(limits=c(0,NA), expand=c(0,0)) + xlab("Nucleotide") + ylab("Shannon Diversity (E_H)") + theme(plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm"))}
```

I have a data frame (39340 x 9) where the columns are chromosome identifier, position, shannon diversity of 7 different samples, and rows are nucleotides. There are 10 chromosomes (3934x10=39340 rows) but I only need a subset from each (hence the ORF start and stop vectors). The loop above will plot 10 ORFs from 1 sample. Eventually, I would like to output the looped plots to a grid divided by row (sample) and column (chromosomes). 

Problem 1) the last plot overwrites the previous ones
Solution 1) plot_list<-list()
for (i in 1:10){
plot_list[[i]]<-ggplot(all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),], aes(all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),2], all_files_sorted[(((i-1)*x)+start[i]):(((i-1)*x)+stop[i]),18])) + geom_line() + scale_x_continuous(limits=c(0,4000), expand=c(0,0)) + scale_y_continuous(limits=c(0,NA), expand=c(0,0)) + xlab("Nucleotide") + ylab("Shannon Diversity (E_H)") + theme(plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm"))}
do.call("grid.arrange", plot_list)
Problem 2) Error: Aesthetics must be either length 1 or the same as the data (3873): x, y

Any help would be greatly appreciated! I am super stuck and have exhausted online resources and people in my vicinity. UBC R Study group is my last hope..

Thank you!

**Comment by arnavs** [comment]
Can you make the work-a-long on Wednesday (Koerner 216, 1 PM?). It'll be mainly planning a workshop, but there should definitely be people capable of helping you (if this is still an issue). Unfortunately I'm not one of those people.

**Comment by ian-flores** [comment]
@j3551ca were you able to solve this issue?

**Comment by j3551ca** [comment]
Not yet. I solved it in MATLAB.
