### ISSUE TITLE
Intro Plotting (gg and friends): Wed, Feb 20

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#32]
Join us in Koerner 216, 1 PM, for a talk presented by @rzitomer

**Comment by ttimbers** [comment]
Hi all, I'm away this week, so sadly I'll miss this one. Can @minisciencegirl or another member take the lead to get the session started and to pass around a sign in sheet.

**Comment by rzitomer** [comment]
I am so so sorry, I didn't realize I was presenting this week and won't be able to make it to campus. Happy to present next week or any other time that is convenient. My sincere apologies, especially for the late notice. @minisciencegirl

**Comment by travis-m-blimkie** [comment]
Hey guys, I can go through the DataCarpentry data visualization lesson, at:
https://datacarpentry.org/R-genomics/05-data-visualization.html

Link to the data:
https://raw.githubusercontent.com/datacarpentry/R-genomics/gh-pages/data/Ecoli_metadata.csv

Cheers!

**Comment by arnavs** [comment]
Thanks for coming through @travis-m-blimkie
