### ISSUE TITLE
Exploratory Data Analysis: Wed, Mar 13

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#35]
Join us in Koerner 216, 1 PM, for a Work-a-long. Bring your R/Julia/Python projects and questions!

**Comment by travis-m-blimkie** [comment]
UPDATE:
Join us in the Koerner Library room 216 at 1pm, for an EDA talk by @aaronquinton

**Comment by jgsmagalhaes** [comment]
Hello Travis, 

I'm having some difficulties with my code, so is it possible to discuss them with one of you? Does the study group offer that?

**Comment by arnavs** [comment]
Yeah, come by during a work a long (or today, depending on how long the talk is) and someone should be able to take a look.

**Comment by ttimbers** [comment]
@arnavs @travis-m-blimkie - can either of you take lead today in getting things going and passing around the sign in sheet? I have been sick since late last week, and am still quite sick today and so won't be able to make it... 😿

**Comment by arnavs** [comment]
Sure, I'll be there and can do it.
