### ISSUE TITLE
Work-a-long: Wed, Mar 27

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#37]
Join us in Koerner 216, 1 PM, for a Work-a-long. Bring your R/Julia/Python projects and questions!

**Comment by jaylu00** [comment]
Hi, I have zero experience on R programme, but I would like to learn some data analysis on my data. Can I still come?

**Comment by arnavs** [comment]
Yes, for sure.

**Comment by jaylu00** [comment]
Thanks! I will bring my laptop and my dataset on 27th March. Thanks a lot!

**Comment by arnavs** [comment]
No problem, see you on Wednesday.
