### ISSUE TITLE
Iteration and purrr::map(): Wed, Apr 17

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#40]
Join us in Koerner 216, 1 PM, for a talk presented by @travis-m-blimkie

**Comment by travis-m-blimkie** [comment]
Hi everyone!
I have added a few files into the lessons folder, under "20190417_map". One is a R script that we will use as a starting point for the live coding stuff. The other two are data files that we will be making use of in some of the examples. 
I've added the script file here to make it easy to access. I will also upload the "master" version of this script after the lesson. 

[map_lesson_20190417.txt](https://github.com/UBC-R-Study-group/studyGroup/files/3090467/map_lesson_20190417.txt)

Cheers!
