### ISSUE TITLE
End-of-Year Party: Wed, May 15

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#44]
Join us in Koerner 216, 1 PM, for the end-of-year party!

**Comment by arnavs** [comment]
Just to check: who is interested in coming to this? We'll be cancelling the other two sessions per #52, but I'm game to organize a party if people will be able to attend.

**Comment by laijasmine** [comment]
I'm out of town so I won't be able to attend unfortunately until  June :(

**Comment by arnavs** [comment]
Travis said he'll be out of town too.

**Comment by arnavs** [comment]
Alright, I guess it’s not to be. @laijasmine you can pull the trigger on your PR whenever.

**Comment by laijasmine** [comment]
@arnavs I don't have write access so I can't merge :( I guess you will have to do it for me.
