### ISSUE TITLE
Differential Gene Expression Analysis

### ISSUE THREAD

**Issue by levanayang** [UBC-R-Study-group/studyGroup#45]
Hi guys,

Is anyone in this group familiar with differential gene expression analysis? I'm pretty new to this, and I have a limma pipeline that I have been using to analyse a couple of Alzheimer's datasets from GEO:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE28146
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE1297

I've tested the pipeline with a larger dataset which seems to work fine, but I've found that I get no differential gene expression results with these other datasets. Each set has around 30 microarray samples and the p-value cut-off is at 0.05 which ends up filtering out the entire set of results. It seems strange to me that there would no be differentially expressed genes in a Alzheimer's patient versus non-Alzheimer's control. Would anyone be able to provide more insight on this?

Thanks for any help.

**Comment by heathervant** [comment]
how big is the dataset? following, because I'm interested in hearing the answer..
