### ISSUE TITLE
Teaching Postdoc position with the UBC Master of Data Science program

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#47]
Hi all!

The University of British Columbia (Vancouver, BC) Master of Data Science program is hiring a Teaching and Learning Postdoctoral Fellow. Come work with a passionate, caring and creative team that has been heavily influenced by the Carpentries.

Job posting: https://www.stat.ubc.ca/postdoctoral-teaching-and-learning-fellow-ubc-master-data-science-program-0

Learn more about the history of our program here: https://ubc-mds.github.io/2019-02-19-designing-mds/ and our students here: https://ubc-mds.github.io/2018-09-17-welcome-2018-19/

Happy to answer any questions through emails to tiffany.timbers@stat.ubc.ca

Best,
Tiffany

**Comment by arnavs** [comment]
@ttimbers Closing as it looks like the March 31st deadline has passed. But if that's more of a soft target, can re-open.
