### ISSUE TITLE
IntroRWorkshop Instructor Meeting March 6

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#48]
Hello all,

As the R workshop is fast approaching, I think it'd be a good idea for us to spend a bit of time at tomorrow's study group session (March 6th) going over everything in preparation for Friday. If all the instructors could be in attendance that'd be great!
@arnavs @ian-flores @laijasmine @abaghela

Cheers!

**Comment by aaronquinton** [comment]
@travis-m-blimkie @minisciencegirl  - I currently have my EDA talk planned for tomorrows study session. Do you think it would be beneficial to switch this with next weeks work along session. This way you will be able to dedicate the time towards preparing for the workshop?

**Comment by aaronquinton** [comment]
Also, this will actually work great for me, because there is an MDS talk with partially overlapping times as our study group time.

**Comment by travis-m-blimkie** [comment]
Sure, let's reschedule your EDA for next week (the 13th), and have today as the work-along and workshop planning. I'll update the README schedule and issues accordingly.

**Comment by ian-flores** [comment]
Sounds good, I'll be able to join today, however I'll be joining at 1:30pm.
