### ISSUE TITLE
Summer Work Learn Position (863011) - Research Assistant, UBC Development and Alumni Engagement

### ISSUE THREAD

**Issue by AmyMatsubara** [UBC-R-Study-group/studyGroup#49]
We are looking for a continuing student to fill our summer Work Learn position! Basic R skills and experience would a great asset. Job ID 863011 https://students.ubc.ca/career/campus-experiences/work-learn-program

**Comment by ian-flores** [comment]
"Thank you for your interest in the Work Learn program! Work Learn Summer 2019 positions are now closed on CareersOnline. If you have any questions regarding the Work Learn program, please contact our office at work.learn@ubc.ca."
