### ISSUE TITLE
R-ladies Event: Creating Résumé/CVs in R & Networking night

### ISSUE THREAD

**Issue by laijasmine** [UBC-R-Study-group/studyGroup#51]
I just started helping the Vancouver R-ladies group organize events! 

Come by our next event on **Fri,  #May 3, 2019, 6:30 PM**. Everyone is welcome to join us at our events and to be a part of our mission to empower gender minorities with the skills and knowledge to code in one of the top programming language in data science, which is R.

Learn how to create Résumé/CVs in R using the package Vitae, followed by some networking discussion specific to the R community and a dinner after (location TBA). 

More details on eventbrite: ****https://www.eventbrite.com/e/creating-resumecvs-in-r-networking-night-tickets-60592965190****

**Comment by travis-m-blimkie** [comment]
Closed as event has passed.
