### ISSUE TITLE
Cancel remaining sessions for the year?

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#52]
@travis-m-blimkie @arnavs @laijasmine - @minisciencegirl and I are sadly over-committed at our jobs and cannot attend the rest of the R Study Group sessions this year. We were thinking that we maybe should cancel them? What do you think?

Going forward, we also sadly cannot commit to running the group due to other work time commitments. We regret that we can no longer do this. If either of you want to take on the torch, that would be very cool and I think the library would support you.

**Comment by ahlyon** [comment]
Thank you so much, all of you, for leading the R Study Group. It’s been a big help and a great experience for me but I understand you needing to manage your commitments. I’m fine with cancelling the rest for the year though I will miss seeing all of you.

**Comment by laijasmine** [comment]
Thank you @ttimbers and @minisciencegirl for making the R-Study groups such a great place to be a beginner in R, ask questions and meet other learners! <3 I have learned so much and now have been way more confident in my R skills. 

On the taking on the torch note.... I would be interested in helping... I am just out of town in the next month but I will follow up afterwards? Hoping to pay it forward to initiate more R learners in the future!

**Comment by arnavs** [comment]
Thanks @ttimbers and @minisciencegirl for all the hard work you did for quite a while with the group. I think it would be hard to live up to that. 

In terms of the sessions this year, I think having an end-of-year party might still be nice. And people would probably turn up? We could do a quick poll or GitHub issue or something, to see who's around town.

As for carrying the torch, I probably wouldn't be able to be the "main" organizer (and that person should probably be more fluent in R than I am...) But I'd definitely be able to assist with things like logistics, git management, doing the semiannual Julia Talk, stuff like that. 

Depending on everyone's availability, it could also work that we take it on as a team the first time around, and then see what people's workloads are like.

**Comment by travis-m-blimkie** [comment]
Thanks to @ttimbers and @minisciencegirl for all of their hard work organizing the study group! You guys did an incredible job. 
I am OK with canceling the next couple sessions. Regarding the end-of-term party, I unfortunately will not be able to attend as I have a conference that day. 
I would be happy to work with a few others to organize the study group in the future. Maybe with the notion of picking things up again come September?

Thanks again to everyone who helped out! Cheers and all the best!

**Comment by laijasmine** [comment]
Sounds good! @travis-m-blimkie , @arnavs I just put in my own calendar to meet Sept 4th since I will never remember anything unless it is in a calendar.

**Comment by arnavs** [comment]
September 4th sounds good to me.

**Comment by minisciencegirl** [comment]
Thank you @laijasmine @travis-m-blimkie @arnavs for the kind words and making this group a wonderful community for #UBC #Rstats. It has been a wonderful experience for myself. Looking forward to passing the torch on to your very capable hands. :-)
