### ISSUE TITLE
Call for TA applications for MDS or Stat 545 in fall of 2019

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#55]
Dear UBC graduate students,

We are accepting applications for TAships with the UBC Master of Data Science (MDS) program and Stat 545. A list of the MDS courses can be viewed here: https://ubc-mds.github.io/descriptions/.  The Master of Data Science program is on the block system, and so each course lasts one month. We ideally want 12 hour/wk TA commitments per course. We welcome students TAing multiple courses. Our blocks fall roughly under these dates:

Block 1: Sept
Block 2: Oct - mid Nov
Block 3: mid Nov - mid Dec

If you are interested, we invite you to please fill out our application form: https://ubc.ca1.qualtrics.com/jfe/form/SV_54EWkqn79DYHbCt

TAing with MDS and/or Stat 545 can help you build and practice both your teaching and Data Science skills. We hope you will consider continuing working with us! If you have any questions about this (or anything related) please do not hesitate to email me or pop by my office (ESB 3152) for a chat :)

Best,
Tiffany

**Comment by ttimbers** [comment]
applications are due June 30th!

**Comment by arnavs** [comment]
Closing this as deadline has passed.
