### ISSUE TITLE
[Paid] R Beginner Workshop: Fri, Oct. 4

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#72]
Join us in Koerner 548/552 at 1 PM for a talk by @laijasmine, @arnavs, @travis-m-blimkie.

**Comment by arnavs** [comment]
You can find the link to this [here](https://tinyurl.com/y2qfb2pk).

**Comment by nesbittios** [comment]
Any chance this workshop could be moved to another day? It conflicts with the Vancouver Climate Strike. Some of my students would like to take it but are also committed to attending the strike.

**Comment by laijasmine** [comment]
Hello Lorien, 

We have heard feedback from individuals interested in the workshop. We have decided to move the workshop to Oct 4th 1-5pm for the Vancouver Climate Strike: https://www.eventbrite.ca/e/r-beginner-workshop-tickets-68936650377

Please let your students know of this change.

Hope to see them at the workshop!

**Comment by nesbittios** [comment]
Great, thanks! I'll pass along the info.
