### ISSUE TITLE
Iteration in R: Wed, Nov. 13

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/studyGroup#79]
Join us in Koerner 548/552 at 1 PM for a talk by @travis-m-blimkie.

**Comment by travis-m-blimkie** [comment]
Link to the lesson for today (save and open with RStudio):
https://raw.githubusercontent.com/UBC-R-Study-group/studyGroup/gh-pages/lessons/20191113_IterationInR/IterationInR_lesson.R

**Comment by travis-m-blimkie** [comment]
Full script/lesson from today is now available, under lessons/20191113_IterationInR/IterationInR_master.R
