### ISSUE TITLE
Call for term 2 UBC Master of Data Science TA applications

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/studyGroup#82]
Dear UBC graduate students,

We are accepting applications for TAships with the UBC Master of Data Science (MDS) program and Stat 547. A list of the MDS courses can be viewed here: https://ubc-mds.github.io/descriptions/. The Master of Data Science program is on the block system, and so each course lasts one month. We ideally want 12 hour/wk TA commitments per course. We welcome students TAing multiple courses. Our blocks fall roughly under these dates:

Block 4 is mid January to mid February, Block 5 is late February to late March, Block 6 is late March to late April.

If you are interested, we invite you to please fill out our application form: https://ubc.ca1.qualtrics.com/jfe/form/SV_8phbioPNSErTxCB

TAing with MDS and/or Stat 547 can help you build and practice both your teaching and Data Science skills. We hope you will consider working with us! If you have any questions about this (or anything related) please do not hesitate to email me :)

Best, Tiffany

tiffany.timbers@stat.ubc.ca

**Comment by ttimbers** [comment]
Just letting everyone know that we are still seeking TAs for term 2!

**Comment by arnavs** [comment]
Closing this as the deadline has passed.
