### ISSUE TITLE
[CANCELLED] Opening session and RMarkdown Introduction: Wed, Jan 15

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#83]
Come to the first R Study Group of the term to hear what's planned, as well as a brief introduction to RMarkdown.

**Comment by idohatam** [comment]
Hi Travis

What time is the next meeting?

Cheers
Ido

**Comment by travis-m-blimkie** [comment]
All study group session are from 1-2pm on Wednesdays, unless otherwise noted.

**Comment by idohatam** [comment]
Thanks

**Comment by travis-m-blimkie** [comment]
UPDATE: Since campus is closed because of the inclement weather, we are also CANCELING the study group session for today. We will move this planned intro session to the following week (Wed Jan 22nd, 1-2pm). The schedule on the README page will be updated accordingly.

Cheers!
