### ISSUE TITLE
Data Transformation in R

### ISSUE THREAD

**Issue by ian-flores** [UBC-R-Study-group/studyGroup#9]
Come learn about data transformation as we work through the Data Transformation Chapter from *R for Data Science*

Session Led by @aemann01

**Where**: Koerner Library, UBC, Room 216

**When**: October 10, 2018 at 01:00:00 PM

**Comment by aemann01** [comment]
Hi everyone! 

If you are planning on coming to the data transformation study session tomorrow please have the tidyverse library installed beforehand. 

```install.packages("tidyverse")```

It takes a bit to install and the session is going to be pretty interactive. Also, you can download the data we're going to play around with [here](https://github.com/aemann01/temp.git)

**Comment by ttimbers** [comment]
@aemann01 - thank-you so much for leading this session. I have to apologize that I will miss it (I am sick with the flu, and none of you probably want it...). See you all next week!

**Comment by arnavs** [comment]
@minisciencegirl and I will be out as well (flu for me, work deadline for her). Do we have signup sheets etc?

**Comment by ian-flores** [comment]
@nazra-inari and I will be collecting the sign-up sheet and helping @aemann01 setting up in whatever comes up.

**Comment by aemann01** [comment]
[Chapter notes](https://github.com/UBC-R-Study-group/studyGroup/files/2466595/notes.txt) from today's session. :grin:
