### ISSUE TITLE
Vancouver Datajam 2020 

### ISSUE THREAD

**Issue by laijasmine** [UBC-R-Study-group/studyGroup#90]
Vancouver Datajam 2020 is a hackathon that focuses on data analysis and visualization. The theme for our datajam will be "Bridging the gap between data and our daily plastics habits". 

Participants will join diverse teams working on preset projects alongside mentors. We welcome individuals of all skill levels and backgrounds.

The datajam will be in three parts:
March 20th 4pm - 8pm - R / Python workshop for beginners
March 21st 9am - 5pm- the datajam hackathon
March 21st 6pm - 9pm - networking event

To learn more or sign up to be a mentor, team lead, participant or volunteer please go to:
https://www.vancouverdatajam.ca/

**Comment by travis-m-blimkie** [comment]
Event has been rescheduled. See https://www.vancouverdatajam.ca/ for more information.
