### ISSUE TITLE
READING WEEK - NO STUDY GROUP

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/studyGroup#91]
Just a reminder that there will be no study group meetup on Wednesday February 19th due to Reading Week. See you all on the 26th!

**Comment by laijasmine** [comment]
Although there isn't a study group tomorrow but the rstudio conference 2020 videos are now online if you want to continue using that hour for R learning!

https://resources.rstudio.com/rstudio-conf-2020
