### ISSUE TITLE
RLadies Data Visualization Workshop - March 5th

### ISSUE THREAD

**Issue by laijasmine** [UBC-R-Study-group/studyGroup#93]
Come join RLadies Vancouver on March 5th for our first event of the year on data visualization with Emma Garlock at Mobify from 6 pm.

More information and RSVP here: 
https://www.eventbrite.com/e/data-visualization-intro-to-ggplot2-tickets-94779071755

**Comment by travis-m-blimkie** [comment]
Closed as is a past event.
